title: Kỉ niệm của Namlete
author: Namlete
email: nguyenlenam15082007@gmail.com
description: >-
  Nơi lưu trữ những bức ảnh kỉ niệm đẹp nhất đối với Namlete

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
