title: Kỉ niệm của Namlete
author: Namlete
email: nguyenlenam15082007@gmail.com
description: >-
  Nơi lưu trữ những bức hình quý giá, đẹp nhất cuộc đời của tôi.

social:
  twitter: Namlete
  facebook: Namlete
  instagram: Namlete
  github: Namlete
  linkedin: Namlete

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
